before:
    hooks:
        - go mod tidy
builds:
    -   binary: unique
        env:
            - CGO_ENABLED=0
        goos:
            - linux
            - darwin
snapshot:
    name_template: "{{ incpatch .Version }}-next"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'

brews:
    -   name: unique
        description: "Outputs the unique lines of its input"
        homepage: "https://github.com/ro-tex/unique"
        license: "MIT"
        directory: Formula
        url_template: "https://github.com/ro-tex/unique/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
        commit_author:
            name: goreleaserbot
            email: bot@goreleaser.com
        commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
        repository:
            owner: ro-tex
            name: homebrew-tap
            branch: main
            token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"
            git:
                url: 'https://github.com/ro-tex/homebrew-tap.git'
                private_key: '/Users/inovakov/.ssh/id_ed25519'
                ssh_command: 'ssh -i /Users/inovakov/.ssh/id_ed25519 -o SomeOption=yes'
